import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const satoshi = localFont({
  src: [
    {
      path: "./fonts/Satoshi-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/Satoshi-Bold.woff2", // Bold version of the font
      weight: "700",
    },
    {
      path: "./fonts/Satoshi-Variable.ttf", // Variable version of the font
      weight: "500 600",
    },
  ],
  variable: "--font-satoshi",
});

const racoleta = localFont({
  src: [
    {
      path: "./fonts/RecoletaAlt-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/Recoleta-Medium.woff2",
      weight: "500",
    },
    {
      path: "./fonts/RecoletaAlt-SemiBold.woff2",
      weight: "400",
    },
    {
      path: "./fonts/Recoleta-Bold.woff2", // Bold version of the font
      weight: "700",
    },
    {
      path: "./fonts/recoleta-regulardemo.otf", // Adding the new Recoleta-RegularDemo.otf font
      weight: "400",
    },
  ],
  variable: "--font-racoleta",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${racoleta.variable} ${satoshi.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
